import type { Config } from 'tailwindcss';

export default {
  content: [
    './packages/docs/index.html',
    './packages/docs/src/**/*.{vue,js,ts,jsx,tsx}',
    './packages/components/src/**/*.{vue,js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          primary: 'var(--color-brand-primary)',
          'primary-hover': 'var(--color-brand-primary-hover)',
          'primary-active': 'var(--color-brand-primary-active)',
          'primary-light': 'var(--color-brand-primary-light)',
          'primary-dark': 'var(--color-brand-primary-dark)',
        },
        semantic: {
          success: 'var(--color-semantic-success)',
          'success-light': 'var(--color-semantic-success-light)',
          'success-dark': 'var(--color-semantic-success-dark)',
          warning: 'var(--color-semantic-warning)',
          'warning-light': 'var(--color-semantic-warning-light)',
          'warning-dark': 'var(--color-semantic-warning-dark)',
          error: 'var(--color-semantic-error)',
          'error-light': 'var(--color-semantic-error-light)',
          'error-dark': 'var(--color-semantic-error-dark)',
          info: 'var(--color-semantic-info)',
          'info-light': 'var(--color-semantic-info-light)',
          'info-dark': 'var(--color-semantic-info-dark)',
        },
        neutral: {
          0: 'var(--color-neutral-0)',
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
        },
      },
      fontFamily: {
        heading: ['Inclusive Sans', 'system-ui', '-apple-system', 'sans-serif'],
        body: ['Outfit', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['Monaco', 'Courier New', 'monospace'],
      },
      fontSize: {
        xs: ['12px', { lineHeight: '1.5' }],
        sm: ['14px', { lineHeight: '1.5' }],
        base: ['16px', { lineHeight: '1.5' }],
        lg: ['18px', { lineHeight: '1.5' }],
        xl: ['20px', { lineHeight: '1.5' }],
        '2xl': ['24px', { lineHeight: '1.375' }],
        '3xl': ['30px', { lineHeight: '1.25' }],
        '4xl': ['36px', { lineHeight: '1.25' }],
        '5xl': ['48px', { lineHeight: '1.25' }],
        '6xl': ['56px', { lineHeight: '1.25' }],
      },
      spacing: {
        0: '0px',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        7: '28px',
        8: '32px',
        9: '36px',
        10: '40px',
        12: '48px',
        14: '56px',
        16: '64px',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-md)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
      },
    },
  },
  plugins: [],
} satisfies Config;
